[package]
name = "vxl"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
glam = "0.30.2"
imgui = "0.12.0"
vk-mem = "0.4.0"
vk-shader-macros = "0.2.10"
winit = "0.30.9"
log = "0.4.21"
