#version 460

layout(local_size_x = 1, local_size_y = 1) in;

layout(rgba16ui,set = 0, binding = 0) uniform uimage2D image;

layout( push_constant ) uniform constants
{
    ivec2 coordinate;
    uint material;
    uint variant;
} PushConstants;


void main()
{
    uvec4 data = imageLoad(image, PushConstants.coordinate);
    data.r = PushConstants.material;
    data.g = PushConstants.variant;
    imageStore(image,PushConstants.coordinate,data);
}