#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba16ui,set = 0, binding = 0) uniform uimage2D image1;
layout(rgba16f,set = 0, binding = 1) uniform image2D image2;

layout( push_constant ) uniform constants
{
    uint swap_io;
    float delta_time;
    vec2 uv_min;
    vec2 uv_max;
    ivec2 batch_offset;
} PushConstants;

void write1(ivec2 coord, uvec4 data);
void write2(ivec2 coord, vec4 data);
void clear(ivec2 coord);

void main()
{
    uvec4 properties1;
    vec4 properties2;

    ivec2 coords = ivec2(gl_GlobalInvocationID.xy) * 3 + PushConstants.batch_offset;
    if (coords.x >= 512) return;
    if (coords.y >= 512) return;
    properties1 = imageLoad(image1, coords);
    if (properties1.r==0) return;
    properties2 = imageLoad(image2, coords);
    properties2.g += PushConstants.delta_time*20; //acceleration
    properties2.a += properties2.g * PushConstants.delta_time;

    int movement = 0;
    if (properties2.a >= 1){
        ivec2 next_coords = coords + ivec2(0,movement+1);
        uvec4 next_properties = imageLoad(image1, next_coords);
        if (next_coords.y >383 || next_properties.r > 0){
            properties2.a = 1;
            properties2.g *= 0.95;
        }else {
            movement += 1;
            properties2.a -= 1;
        }
    }
    if (movement>0){
        clear(coords);
    }else{
        write2(coords,properties2);
    }
    coords += ivec2(0,movement);
    write1(coords,properties1);
    write2(coords,properties2);
}

void write1(ivec2 coord,uvec4 data){
    imageStore(image1,coord,data);
}

void write2(ivec2 coord,vec4 data){
    imageStore(image2,coord,data);
}

void clear(ivec2 coord){
    write1(coord,uvec4(0,0,0,0));
    write2(coord,vec4(0.0,0.0,0.0,0.0));
}
